if !def(ACHARMAP_INC)
def ACHARMAP_INC equ 1

charmap "0", $00
charmap "1", $01
charmap "2", $02
charmap "3", $03
charmap "4", $04
charmap "5", $05
charmap "6", $06
charmap "7", $07
charmap "8", $08
charmap "9", $09
charmap "A", $0A
charmap "B", $0B
charmap "C", $0C
charmap "D", $0D
charmap "E", $0E
charmap "F", $0F
charmap "G", $10
charmap "H", $11
charmap "I", $12
charmap "J", $13
charmap "K", $14
charmap "L", $15
charmap "M", $16
charmap "N", $17
charmap "O", $18
charmap "P", $19
charmap "Q", $1A
charmap "R", $1B
charmap "S", $1C
charmap "T", $1D
charmap "U", $1E
charmap "V", $1F
charmap "W", $20
charmap "X", $21
charmap "Y", $22
charmap "Z", $23
charmap "[", $24
charmap "\\", $25
charmap "]", $26
charmap "^", $27
charmap "_", $28
charmap "`", $29
charmap "a", $2A
charmap "b", $2B
charmap "c", $2C
charmap "d", $2D
charmap "e", $2E
charmap "f", $2F
charmap "g", $30
charmap "h", $31
charmap "i", $32
charmap "j", $33
charmap "k", $34
charmap "l", $35
charmap "m", $36
charmap "n", $37
charmap "o", $38
charmap "p", $39
charmap "q", $3A
charmap "r", $3B
charmap "s", $3C
charmap "t", $3D
charmap "u", $3E
charmap "v", $3F
charmap "w", $40
charmap "x", $41
charmap "y", $42
charmap "z", $43
charmap "\{", $44
charmap "|", $45
charmap "\}", $46
charmap "~", $47
charmap ":", $48
charmap ";", $49
charmap "<", $4A
charmap "=", $4B
charmap ">", $4C
charmap "?", $4D
charmap "@", $4E
charmap "!", $4F
charmap "\"", $50
charmap "#", $51
charmap "$", $52
charmap "%", $53
charmap "&", $54
charmap "'", $55
charmap "(", $56
charmap ")", $57
charmap "*", $58
charmap "+", $59
charmap ",", $5A
charmap "-", $5B
charmap ".", $5C
charmap "/", $5D
charmap " ", $5E
; $5F

; afont-extra
charmap "^yes^", $60
charmap "^no^", $61
charmap "^rx^", $62
charmap "^tx^", $63

endc ; ACHARMAP_INC


;
; vim:ft=rgbasm
